import { describe, expect, it, vi } from 'vitest'
import { SideChatController } from '../../src/client/side-chat-controller.js'
import { SessionId, SideChatId, type ConversationSelection } from '../../src/shared/contracts.js'
import { deferred, FakeClientSessions, FakeRemote, MODEL } from '../fixtures/client-runtime.js'

const selection: ConversationSelection = {
  parentSessionId: SessionId('parent-1'), text: 'Selected <text>', atSeq: 7, fragments: [],
  rect: { x: 0, y: 0, width: 10, height: 10, viewportWidth: 800, viewportHeight: 600 },
}
function fixture() {
  const remote = new FakeRemote()
  const sessions = new FakeClientSessions()
  const controller = new SideChatController(remote, sessions)
  return { remote, sessions, controller }
}
describe('read-only Side Chat controller', () => {
  it('creates nothing until send, pins only the parent, and sends plain question text', async () => {
    const { controller, remote, sessions } = fixture()
    expect(controller.openDraft({ selection }).ok).toBe(true)
    expect(remote.createCalls).toHaveLength(0)
    expect(sessions.parentsRetained).toBe(1)
    expect((await controller.sendFirst('Why <this> & that?')).ok).toBe(true)
    expect(remote.createCalls[0]).toMatchObject({ parentSessionId: 'parent-1', atSeq: 7, selectedText: selection.text })
    expect(remote.streamCalls[0]?.text).toBe('Why <this> & that?')
    expect(controller.getSnapshot().messages[0]).toMatchObject({ role: 'user', text: 'Why <this> & that?', selectedText: selection.text })
    expect(sessions.opened).toEqual([])
    await controller.close()
    expect(remote.streams[0]?.disposed).toBe(true)
    expect(sessions.parentsRetained).toBe(0)
    expect(controller.getSnapshot()).toMatchObject({ phase: 'closed', messages: [] })
  })
  it('streams updates and keeps subsequent questions separate from the initial annotation', async () => {
    const { controller, remote } = fixture()
    controller.openDraft({ selection })
    await controller.sendFirst('Why?')
    remote.streams[0]!.push({ type: 'content', text: 'An answer', reasoning: 'A reason' })
    remote.streams[0]!.finish()
    await vi.waitFor(() => expect(controller.getSnapshot().phase).toBe('ready'))
    expect(controller.getSnapshot().messages[1]).toMatchObject({ text: 'An answer', reasoning: 'A reason', status: 'complete' })
    await controller.send('And next?')
    expect(remote.createCalls).toHaveLength(1)
    expect(controller.getSnapshot().messages[2]?.selectedText).toBeUndefined()
    await controller.dispose()
  })
  it('refuses stale selections without creating a discussion', async () => {
    const { controller, remote, sessions } = fixture()
    controller.openDraft({ selection })
    sessions.selectionCurrent = false
    expect((await controller.sendFirst('Why?')).ok).toBe(false)
    expect(remote.createCalls).toHaveLength(0)
    await controller.dispose()
  })
  it('closes a late create without ever starting a model stream', async () => {
    const { controller, remote } = fixture()
    remote.createDeferred = deferred<Awaited<ReturnType<FakeRemote['create']>>>()
    controller.openDraft()
    const sent = controller.sendFirst('Why?')
    const closed = controller.close()
    remote.createDeferred.resolve({ ok: true, value: { parentSessionId: SessionId('parent-1'),
      chatId: SideChatId('late'), boundarySeq: 7, modelSelection: MODEL } })
    expect((await sent).ok).toBe(false)
    expect((await closed).ok).toBe(true)
    expect(remote.closeCalls).toEqual([{ chatId: 'late' }])
    expect(remote.streamCalls).toHaveLength(0)
  })
  it('retries an unobserved admission with the same request identity and captured context', async () => {
    const { controller, remote, sessions } = fixture()
    remote.autoStart = false
    controller.openDraft({ selection })
    const first = controller.sendFirst('Question')
    await vi.waitFor(() => expect(remote.streams).toHaveLength(1))
    remote.streams[0]!.push({ type: 'error', error: { code: 'transport_error', message: 'Retry delivery', recoverable: true } })
    expect((await first).ok).toBe(false)
    sessions.lastSeq = undefined
    sessions.selectionCurrent = false
    remote.autoStart = true
    expect((await controller.retry()).ok).toBe(true)
    expect(remote.createCalls).toHaveLength(1)
    expect(remote.streamCalls[1]?.requestId).toBe(remote.streamCalls[0]?.requestId)
    await controller.dispose()
  })
  it('does not replay an admitted question after a model failure', async () => {
    const { controller, remote } = fixture()
    controller.openDraft()
    await controller.sendFirst('Question')
    remote.streams[0]!.push({ type: 'error', error: { code: 'side_chat_prompt_failed', message: 'Provider failed', recoverable: true } })
    await vi.waitFor(() => expect(controller.getSnapshot().error?.message).toBe('Provider failed'))
    expect(controller.getSnapshot().error?.recoverable).toBe(false)
    expect((await controller.retry()).ok).toBe(false)
    expect(remote.streamCalls).toHaveLength(1)
    expect((await controller.send('Try a different question')).ok).toBe(true)
    await controller.dispose()
  })
  it('cancels the carrier before admission and keeps the unsent draft', async () => {
    const { controller, remote } = fixture()
    remote.autoStart = false
    controller.openDraft()
    const sent = controller.sendFirst('Keep me')
    await vi.waitFor(() => expect(remote.streams).toHaveLength(1))
    await controller.cancel()
    expect((await sent).ok).toBe(false)
    expect(remote.streams[0]?.disposed).toBe(true)
    expect(controller.getSnapshot()).toMatchObject({ phase: 'ready', draft: 'Keep me', messages: [] })
    remote.autoStart = true
    expect((await controller.sendFirst('Keep me')).ok).toBe(true)
    expect(remote.streamCalls[1]?.requestId).not.toBe(remote.streamCalls[0]?.requestId)
    await controller.dispose()
  })
  it('stops a partial reply without calling any parent Agent controls', async () => {
    const { controller, remote, sessions } = fixture()
    controller.openDraft()
    await controller.sendFirst('Question')
    remote.streams[0]!.push({ type: 'content', text: 'Partial', reasoning: '' })
    await vi.waitFor(() => expect(controller.getSnapshot().messages[1]?.text).toBe('Partial'))
    await controller.cancel()
    await vi.waitFor(() => expect(controller.getSnapshot().messages[1]?.status).toBe('stopped'))
    expect(remote.cancelCalls).toEqual([{ chatId: 'side-chat-1' }])
    expect(sessions.current).toBe('parent-1')
    expect(sessions.opened).toEqual([])
    await controller.dispose()
  })
  it('saves reasoning changes during generation for follow-ups and the next More details discussion', async () => {
    const { controller, remote, sessions } = fixture()
    controller.openDraft({ selection })
    await controller.sendFirst('Question')
    const chosen = { ...MODEL, reasoningEffort: 'high' }
    expect((await controller.selectModel(chosen)).ok).toBe(true)
    expect(controller.getSnapshot()).toMatchObject({ phase: 'running', modelSelection: chosen })
    expect(sessions.modelPreference).toEqual(chosen)
    expect(remote.streamModels[0]).toEqual(MODEL)
    expect(remote.cancelCalls).toHaveLength(0)

    remote.streams[0]!.finish()
    await vi.waitFor(() => expect(controller.getSnapshot().phase).toBe('ready'))
    await controller.send('Follow-up')
    expect(remote.streamModels[1]).toEqual(chosen)
    await controller.close()
    controller.openDraft({ selection })
    await controller.sendFirst('Please explain the selected passage in more detail.')
    expect(remote.createCalls[1]?.modelSelection).toEqual(chosen)
    expect(remote.streamModels[2]).toEqual(chosen)
    expect(sessions.opened).toEqual([])
    await controller.dispose()
  })
  it('does not let a delayed admission overwrite a newer reasoning choice', async () => {
    const { controller, remote, sessions } = fixture()
    controller.openDraft()
    await controller.sendFirst('First')
    remote.streams[0]!.finish()
    await vi.waitFor(() => expect(controller.getSnapshot().phase).toBe('ready'))
    remote.autoStart = false
    const sent = controller.send('Follow-up')
    const chosen = { ...MODEL, reasoningEffort: 'high' }
    expect((await controller.selectModel(chosen)).ok).toBe(true)
    remote.streams[1]!.push({ type: 'started', requestId: remote.streamCalls[1]!.requestId, modelSelection: MODEL })
    expect((await sent).ok).toBe(true)
    expect(controller.getSnapshot().modelSelection).toEqual(chosen)
    expect(sessions.modelPreference).toEqual(chosen)
    await controller.dispose()
  })
  it('does not let replaying an older request reset the saved reasoning choice', async () => {
    const { controller, remote, sessions } = fixture()
    controller.openDraft()
    await controller.sendFirst('First')
    remote.streams[0]!.finish()
    await vi.waitFor(() => expect(controller.getSnapshot().phase).toBe('ready'))
    remote.autoStart = false
    const original = controller.send('Follow-up')
    remote.streams[1]!.push({ type: 'error', error: { code: 'transport_error', message: 'Admission lost', recoverable: true } })
    expect((await original).ok).toBe(false)
    const chosen = { ...MODEL, reasoningEffort: 'high' }
    await controller.selectModel(chosen)
    const retried = controller.retry()
    expect(remote.streamCalls[2]?.requestId).toBe(remote.streamCalls[1]?.requestId)
    remote.streams[2]!.push({ type: 'started', requestId: remote.streamCalls[2]!.requestId, modelSelection: MODEL })
    expect((await retried).ok).toBe(true)
    expect(controller.getSnapshot().modelSelection).toEqual(chosen)
    expect(sessions.modelPreference).toEqual(chosen)
    await controller.dispose()
  })
  it('keeps the previous preference when a running-time reasoning change is rejected', async () => {
    const { controller, remote, sessions } = fixture()
    controller.openDraft()
    await controller.sendFirst('Question')
    vi.spyOn(remote, 'selectModel').mockRejectedValue(new Error('Unsupported effort'))
    expect((await controller.selectModel({ ...MODEL, reasoningEffort: 'unsupported' })).ok).toBe(false)
    expect(controller.getSnapshot()).toMatchObject({ phase: 'running', modelSelection: MODEL })
    expect(sessions.modelPreference).toEqual(MODEL)
    expect(remote.cancelCalls).toHaveLength(0)
    await controller.dispose()
  })
  it('keeps model selection local to the discussion and ignores late results after close', async () => {
    const { controller, remote, sessions } = fixture()
    controller.openDraft()
    await controller.selectModel({ provider: 'saved', model: 'saved-model' })
    expect(sessions.modelPreference?.model).toBe('saved-model')
    await controller.sendFirst('Question')
    await controller.cancel()
    const selected = deferred<Awaited<ReturnType<FakeRemote['selectModel']>>>()
    vi.spyOn(remote, 'selectModel').mockImplementation(() => selected.promise)
    const changed = controller.selectModel({ provider: 'late', model: 'late' })
    await controller.close()
    controller.openDraft()
    selected.resolve({ ok: true, value: { selected: { provider: 'late', model: 'late', reasoningEffort: undefined } } })
    await changed
    expect(controller.getSnapshot().modelSelection?.model).not.toBe('late')
    await controller.dispose()
  })
  it('still closes the Host discussion when carrier disposal throws', async () => {
    const { controller, remote, sessions } = fixture()
    controller.openDraft()
    await controller.sendFirst('Question')
    const stream = remote.streams[0]!
    const dispose = stream.dispose.bind(stream)
    vi.spyOn(stream, 'dispose').mockImplementation(() => { dispose(); throw new Error('Carrier already closed') })
    expect((await controller.close()).ok).toBe(true)
    expect(remote.closeCalls).toEqual([{ chatId: 'side-chat-1' }])
    expect(sessions.parentsRetained).toBe(0)
  })
  it('retains a failed close for retry without resending any prompt', async () => {
    const { controller, remote } = fixture()
    controller.openDraft()
    await controller.sendFirst('Question')
    remote.closeResults.push({ ok: false, error: { code: 'transport_error', message: 'offline', recoverable: true } })
    expect((await controller.close()).ok).toBe(false)
    expect(controller.getSnapshot().error?.operation).toBe('close')
    expect((await controller.retry()).ok).toBe(true)
    expect(remote.streamCalls).toHaveLength(1)
  })
})
